/**
 * @providesModule ZeroProj.Redux.Types
 */

// Auth action types
export const AUTH = {
  CHANGE_ACCESS_LEVEL:        'CHANGE_ACCESS_LEVEL',
  SIGN_IN_WITH_PASSWORD:      'SIGN_IN_WITH_PASSWORD',
  SIGN_IN_WITH_PROVIDER:      'SIGN_IN_WITH_PROVIDER',
  SIGN_OUT:                   'SIGN_OUT',
};

// Common action types
export const COMMONS = {
  REQUEST_REMOTE_RESOURCES:   'REQUEST_REMOTE_RESOURCES',
  TOGGLE_LOADING_SPINNER:     'TOGGLE_LOADING_SPINNER',
  TOGGLE_REFRESH_CONTROL:     'TOGGLE_REFRESH_CONTROL',
  UPDATE_LOADING_PROGRESS:    'UPDATE_LOADING_PROGRESS',
  UPDATE_USER_LOCATION:       'UPDATE_USER_LOCATION',
};
